[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["npm install --no-fund"]

[phases.build]
cmds = [
  "chmod +x build.sh",
  "./build.sh"
]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"

[nixpacks]
plan-path = "/tmp/nixpacks.plan"

[[nixpacks.cache]]
dir = "/tmp/next-cache"
type = "shared"

[[nixpacks.cache]]
dir = "/tmp/node_cache"
type = "shared"
