[phases.setup]
nixpkgs = ["nodejs", "nodePackages.npm", "postgresql"]

[phases.install]
cmds = [
  "cd backend && npm ci",
  "cd ../frontend && npm ci"
]

[phases.build]
cmds = [
  "cd backend && npx prisma generate",
  "cd backend && npm run build || true",
  "cd ../frontend && npm run build"
]

[start]
cmd = "cd backend && node dist/main.js" 