[phases.setup]
nixpkgs = ["nodejs", "nodePackages.npm", "postgresql"]
cmds = [
  "node --version",
  "npm --version"
]

[phases.install]
cmds = [
  "cd backend && npm ci --no-fund --prefer-offline --no-audit",
  "cd ../frontend && npm ci --no-fund --prefer-offline --no-audit"
]

[phases.build]
cmds = [
  "cd backend && npx prisma generate",
  "cd backend && npm run build || true",
  "cd ../frontend && npm run build"
]

[start]
cmd = "cd backend && node dist/main.js" 