[phases.setup]
nixPkgs = ['nodejs_20']
nixOverlays = []
nixpkgsArchive = "ffeebf0acf3ae8b29f8c7049cd911b9636efd7e7"

[phases.install]
cmds = ['cd backend && npm install']

[phases.build]
cmds = ['cd backend && npx tsc || true']

[start]
cmd = 'cd backend && npm run start:prod' 