[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["npm install --no-fund"]

[phases.build]
cmds = [
  "npm run prisma:generate",
  "npm run build || true"
]

[start]
cmd = "npm run start:prod"

[variables]
NODE_ENV = "production"
CACHE_DIR = "/tmp/node_cache"

[nixpacks]
plan-path = "/tmp/nixpacks.plan"