[build]
builder = "nixpacks"
buildCommand = "npm run build || true"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[nixpacks]
cache-dir = "/tmp/node_cache"